package runtime.registry

/**
 * Maps items to their numeric IDs
 */
object ItemRegistry {
    private val byName: Map<String, Int> = mapOf(
        "air" to 0,
        "stone" to 1,
        "grass" to 2,
        "dirt" to 3,
        "cobblestone" to 4,
        "planks" to 5,
        "sapling" to 6,
        "bedrock" to 7,
        "flowing_water" to 8,
        "water" to 9,
        "flowing_lava" to 10,
        "lava" to 11,
        "sand" to 12,
        "gravel" to 13,
        "gold_ore" to 14,
        "iron_ore" to 15,
        "coal_ore" to 16,
        "log" to 17,
        "leaves" to 18,
        "sponge" to 19,
        "glass" to 20,
        "lapis_ore" to 21,
        "lapis_block" to 22,
        "dispenser" to 23,
        "sandstone" to 24,
        "noteblock" to 25,
        "bed" to 26,
        "golden_rail" to 27,
        "detector_rail" to 28,
        "sticky_piston" to 29,
        "web" to 30,
        "tallgrass" to 31,
        "deadbush" to 32,
        "piston" to 33,
        "piston_head" to 34,
        "wool" to 35,
        "piston_extension" to 36,
        "yellow_flower" to 37,
        "red_flower" to 38,
        "brown_mushroom" to 39,
        "red_mushroom" to 40,
        "gold_block" to 41,
        "iron_block" to 42,
        "double_stone_slab" to 43,
        "stone_slab" to 44,
        "brick_block" to 45,
        "tnt" to 46,
        "bookshelf" to 47,
        "mossy_cobblestone" to 48,
        "obsidian" to 49,
        "torch" to 50,
        "fire" to 51,
        "mob_spawner" to 52,
        "oak_stairs" to 53,
        "chest" to 54,
        "redstone_wire" to 55,
        "diamond_ore" to 56,
        "diamond_block" to 57,
        "crafting_table" to 58,
        "wheat" to 59,
        "farmland" to 60,
        "furnace" to 61,
        "lit_furnace" to 62,
        "standing_sign" to 63,
        "wooden_door" to 64,
        "ladder" to 65,
        "rail" to 66,
        "stone_stairs" to 67,
        "wall_sign" to 68,
        "lever" to 69,
        "stone_pressure_plate" to 70,
        "iron_door" to 71,
        "wooden_pressure_plate" to 72,
        "redstone_ore" to 73,
        "lit_redstone_ore" to 74,
        "unlit_redstone_torch" to 75,
        "redstone_torch" to 76,
        "stone_button" to 77,
        "snow_layer" to 78,
        "ice" to 79,
        "snow" to 80,
        "cactus" to 81,
        "clay" to 82,
        "reeds" to 83,
        "jukebox" to 84,
        "fence" to 85,
        "pumpkin" to 86,
        "netherrack" to 87,
        "soul_sand" to 88,
        "glowstone" to 89,
        "portal" to 90,
        "lit_pumpkin" to 91,
        "cake" to 92,
        "unpowered_repeater" to 93,
        "powered_repeater" to 94,
        "stained_glass" to 95,
        "trapdoor" to 96,
        "monster_egg" to 97,
        "stonebrick" to 98,
        "brown_mushroom_block" to 99,
        "red_mushroom_block" to 100,
        "iron_bars" to 101,
        "glass_pane" to 102,
        "melon_block" to 103,
        "pumpkin_stem" to 104,
        "melon_stem" to 105,
        "vine" to 106,
        "fence_gate" to 107,
        "brick_stairs" to 108,
        "stone_brick_stairs" to 109,
        "mycelium" to 110,
        "waterlily" to 111,
        "nether_brick" to 112,
        "nether_brick_fence" to 113,
        "nether_brick_stairs" to 114,
        "nether_wart" to 115,
        "enchanting_table" to 116,
        "brewing_stand" to 117,
        "cauldron" to 118,
        "end_portal" to 119,
        "end_portal_frame" to 120,
        "end_stone" to 121,
        "dragon_egg" to 122,
        "redstone_lamp" to 123,
        "lit_redstone_lamp" to 124,
        "double_wooden_slab" to 125,
        "wooden_slab" to 126,
        "cocoa" to 127,

        "oak_planks" to 128,
        "spruce_planks" to 129,
        "birch_planks" to 130,
        "jungle_planks" to 131,
        "acacia_planks" to 132,
        "dark_oak_planks" to 133,

        "oak_sapling" to 134,
        "spruce_sapling" to 135,
        "birch_sapling" to 136,
        "jungle_sapling" to 137,
        "acacia_sapling" to 138,
        "dark_oak_sapling" to 139,

        "oak_leaves" to 140,
        "spruce_leaves" to 141,
        "birch_leaves" to 142,
        "jungle_leaves" to 143,

        "sandstone_normal" to 144,
        "sandstone_chiseled" to 145,
        "sandstone_smooth" to 146,

        "stone_bricks" to 147,
        "mossy_stone_bricks" to 148,
        "cracked_stone_bricks" to 149,
        "chiseled_stone_bricks" to 150,

        "wool_white" to 151,
        "wool_orange" to 152,
        "wool_magenta" to 153,
        "wool_light_blue" to 154,
        "wool_yellow" to 155,
        "wool_lime" to 156,
        "wool_pink" to 157,
        "wool_gray" to 158,
        "wool_light_gray" to 159,
        "wool_cyan" to 160,
        "wool_purple" to 161,
        "wool_blue" to 162,
        "wool_brown" to 163,
        "wool_green" to 164,
        "wool_red" to 165,
        "wool_black" to 166,

        "stained_glass_white" to 167,
        "stained_glass_orange" to 168,
        "stained_glass_magenta" to 169,
        "stained_glass_light_blue" to 170,
        "stained_glass_yellow" to 171,
        "stained_glass_lime" to 172,
        "stained_glass_pink" to 173,
        "stained_glass_gray" to 174,
        "stained_glass_light_gray" to 175,
        "stained_glass_cyan" to 176,
        "stained_glass_purple" to 177,
        "stained_glass_blue" to 178,
        "stained_glass_brown" to 179,
        "stained_glass_green" to 180,
        "stained_glass_red" to 181,
        "stained_glass_black" to 182
    )

    /**
     * Looks up the numeric ID of an item by its name (case insensitive)
     *
     * @param name The item name
     * @return The numeric ID, or null if not found
     */
    fun idOf(name: String): Int? = byName[name.lowercase()]
}