say wooden_pressure_plate to string
say iron_bars to string
say brick_stairs to string
say brick_stairs to string
say waterlily to string
say flowing_lava to string
say end_portal to string
say waterlily to string
say nether_brick_stairs to string
say brick_stairs to string
say red_mushroom_block to string